### ISSUE TITLE
Error - [nodemon] app crashed

### ISSUE THREAD

**Issue by raymondfx** [kiva/aries-guardianship-agency#95]
I am getting this issue when i try to run 

```aries-guardianship-agency    | 
aries-guardianship-agency    | /www/node_modules/jose/lib/help/rsa_primes.js:6
aries-guardianship-agency    | const ZERO = BigInt(0)
aries-guardianship-agency    |              ^
aries-guardianship-agency    | ReferenceError: BigInt is not defined
aries-guardianship-agency    |     at Object.<anonymous> (/www/node_modules/jose/lib/help/rsa_primes.js:6:14)
aries-guardianship-agency    |     at Module._compile (module.js:653:30)
aries-guardianship-agency    |     at Object.Module._extensions..js (module.js:664:10)
aries-guardianship-agency    |     at Module.load (module.js:566:32)
aries-guardianship-agency    |     at tryModuleLoad (module.js:506:12)
aries-guardianship-agency    |     at Function.Module._load (module.js:498:3)
aries-guardianship-agency    |     at Module.require (module.js:597:17)
aries-guardianship-agency    |     at require (internal/module.js:11:18)
aries-guardianship-agency    |     at Object.<anonymous> (/www/node_modules/jose/lib/help/key_utils.js:9:23)
aries-guardianship-agency    |     at Module._compile (module.js:653:30)
aries-guardianship-agency    | [nodemon] app crashed - waiting for file changes before starting...```

**Comment by jsaur** [comment]
Hi, can you provide more detail on the steps that lead up to this error? It looks from the error message like the issue is in the node module jose, but we don't use that module...
